"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { saveCampaignIntake } from "@/app/actions/submissions";

export default function CampaignIntake({ token }: { token: string }) {
  const router = useRouter(); const [language, setLanguage] = useState("en"); const [name, setName] = useState(""); const [agentId, setAgentId] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,_#dceaff,_#f5f8fc_45%)] px-5 py-10"><div className="mx-auto max-w-2xl rounded-3xl bg-white p-7 shadow-xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-ignite">Campaign setup</p><h1 className="mt-2 text-3xl font-bold text-mahogany">Before we start</h1><p className="mt-2 text-sm text-mahogany/60">Choose your language and provide your details once. They will be used for all campaign material submissions.</p><div className="mt-7 space-y-5"><div><p className="mb-2 text-sm font-semibold text-mahogany">Preferred language</p><div className="grid gap-2 sm:grid-cols-3">{[["en","English"],["ms","Bahasa Melayu"],["zh","中文"]].map(([code,label]) => <button type="button" key={code} onClick={() => setLanguage(code)} className={`rounded-xl border px-4 py-3 text-sm font-semibold ${language === code ? "border-ignite bg-ignite/5 text-ignite" : "border-crystal text-mahogany"}`}>{label}</button>)}</div></div><label className="block text-sm font-semibold text-mahogany">Full name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 block w-full rounded-lg border border-crystal px-3 py-2 font-normal focus:border-ignite focus:outline-none" /></label><label className="block text-sm font-semibold text-mahogany">Agent ID<input value={agentId} onChange={(event) => setAgentId(event.target.value)} className="mt-1 block w-full rounded-lg border border-crystal px-3 py-2 font-normal focus:border-ignite focus:outline-none" /></label>{error && <p className="text-sm text-red-600">{error}</p>}<button type="button" disabled={pending} onClick={() => startTransition(async () => { const result = await saveCampaignIntake(token, language, name, agentId); if (result.ok) router.refresh(); else setError(result.error); })} className="w-full rounded-xl bg-ignite px-4 py-3 text-sm font-bold text-white hover:bg-ignite-hover disabled:opacity-50">{pending ? "Saving..." : "Continue to campaign materials"}</button></div></div></main>;
}
