"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { saveCampaignIntake } from "@/app/actions/submissions";
import { translations, type Language } from "@/lib/i18n";

export default function CampaignIntake({ token }: { token: string }) {
  const router = useRouter(); const [language, setLanguage] = useState<Language>("en"); const [name, setName] = useState(""); const [agentId, setAgentId] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const t = translations[language];
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,_#dceaff,_#f5f8fc_45%)] px-5 py-10"><div className="mx-auto max-w-2xl overflow-hidden rounded-[2rem] border border-white/70 bg-white shadow-2xl shadow-[#172b5424]"><div className="border-b border-crystal bg-[linear-gradient(135deg,_#fff,_#f5f9ff)] px-7 pb-7 pt-9 text-center sm:px-10"><div className="mx-auto w-fit rounded-xl bg-white px-5 py-3 shadow-sm"><Image src="/brands/propertyguru-iproperty-dual.png" alt="PropertyGuru and iProperty" width={400} height={94} priority className="h-auto w-full max-w-[320px] object-contain" /></div><p className="mt-7 text-[11px] font-semibold uppercase tracking-[0.28em] text-mahogany/70">Performance Marketing · Meta Ads</p><p className="mt-2 text-sm leading-6 text-mahogany/60">Thank you for choosing PropertyGuru and iProperty for your campaign.</p></div><div className="p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-ignite">{t.campaignSetup}</p><h1 className="mt-2 text-3xl font-bold text-mahogany">{t.beforeWeStart}</h1><p className="mt-2 text-sm leading-6 text-mahogany/60">{t.campaignIntakeHint}</p><div className="mt-7 space-y-5"><div><p className="mb-2 text-sm font-semibold text-mahogany">{t.preferredLanguage}</p><div className="grid gap-2 sm:grid-cols-3">{[["en","English"],["ms","Bahasa Melayu"],["zh","中文"]].map(([code,label]) => <button type="button" key={code} onClick={() => setLanguage(code as Language)} className={`rounded-xl border px-4 py-3 text-sm font-semibold ${language === code ? "border-ignite bg-ignite/5 text-ignite" : "border-crystal text-mahogany"}`}>{label}</button>)}</div></div><label className="block text-sm font-semibold text-mahogany">{t.fullName}<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 block w-full rounded-lg border border-crystal px-3 py-2 font-normal focus:border-ignite focus:outline-none" /></label><label className="block text-sm font-semibold text-mahogany">{t.agentId}<input value={agentId} onChange={(event) => setAgentId(event.target.value)} className="mt-1 block w-full rounded-lg border border-crystal px-3 py-2 font-normal focus:border-ignite focus:outline-none" /></label>{error && <p className="text-sm text-red-600">{error}</p>}<button type="button" disabled={pending} onClick={() => startTransition(async () => { const result = await saveCampaignIntake(token, language, name, agentId); if (result.ok) router.refresh(); else setError(result.error); })} className="w-full rounded-xl bg-ignite px-4 py-3 text-sm font-bold text-white hover:bg-ignite-hover disabled:opacity-50">{pending ? t.saving : t.continueToMaterials}</button></div></div></div></main>;
}
